apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: improvingdeveloperworkflow
build:
  artifacts:
    - image: my-cool-app
      context: src
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
